import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import { NavbarDemo } from "./Header";
=======
import Header from "./Header";
>>>>>>> fc0e86f0d21ca784de76c8f4b171dccee5526836

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <NavbarDemo />
=======
        <Header />
>>>>>>> fc0e86f0d21ca784de76c8f4b171dccee5526836
        {children}
      </body>
    </html>
  );
}
